# Copyright (c) NetworkFusion, .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

# This workflow will build push the sln to a hardware target.

name: Build and push

on: [push, pull_request]

defaults:
  run:
    shell: pwsh
    
jobs:
  build-solution:
    name: Build nanoFramework solution
    timeout-minutes: 15
    runs-on: self-hosted
    env:
      solution: 'AwsEdukitM5Core2.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'
      GITHUB_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # not required on selfhost as already installed (and action cannot handle it).
      # - name: Install build components for nanoFramework
      #   uses: nanoframework/nanobuild@v1

      - name: Setup MSBuild Path
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - name: Install NuGet client
        uses: nuget/setup-nuget@v1

      - name: Restore nuget packages
        run: nuget restore ${{ env.solution }} -ConfigFile NuGet.Config

      # Adjust secrets template to add SSID and PW (TODO: in future should be able to load from a template)
      - name: Use Secrets class template for tests
        run: Copy-Item './AwsEdukitM5Core2/Secrets.cs.template' -Destination './AwsEdukitM5Core2/Secrets.cs'

      # Adjust run settings for tests to run on real hardware.
      # - name: Adjust tests for targeting real hardware devices
      #   run: (Get-Content ./Tests/IntegrationTests/nano.runsettings -Raw) -Replace '<IsRealHardware>False</IsRealHardware>', '<IsRealHardware>True</IsRealHardware>' | Set-Content ./Tests/IntegrationTests/nano.runsettings
      
      - name: Build solution
        run: msbuild ${{ env.solution }} /p:Configuration=${{ env.buildConfiguration }}

      # - name: Run unit tests
      # adjust runsettings to run on real target
      #   run: ./nanoFramework.nanoCLR.exe -load ...nanoFramework.UnitTestLauncher.pe --load ..mscorlib.pe --load ...nanoFramework.TestFramework.pe --load ...NFUnitTest.pe

      # Self hosted runners need to cleanup after themselves. It is important as might have secrets!
      # TODO: this does not clean it up properly!
      - name: Cleanup Runner workspace path
        run: |
          Remove-Item -path ${{ github.workspace }}/* -Recurse
